import seaborn as sns
import matplotlib.pyplot as plt
iris = sns.load_dataset('iris')
print(iris.info())
print(iris.describe())
sns.scatterplot(data=iris, x='sepal_length', y='sepal_width', hue='species')
plt.title('Scatterplot of Sepal Length vs. Sepal Width')
plt.xlabel('Sepal Length')
plt.ylabel('Sepal Width')
plt.show()
sns.boxplot(data=iris, x='species', y='petal_length', palette='Set1')
plt.title('Boxplot of Petal Length by Species')
plt.xlabel('Species')
plt.ylabel('Petal Length')
plt.show()
sns.histplot(data=iris, x='sepal_length', bins=20, kde=True, color='lightblue')
plt.title('Histogram of Sepal Length')
plt.xlabel('Sepal Length')
plt.ylabel('Frequency')
plt.show()
sns.kdeplot(data=iris, x='petal_width', hue='species', fill=True, common_norm=False)
plt.title('Density Plot of Petal Width by Species')
plt.xlabel('Petal Width')
plt.ylabel('Density')
plt.show()
